# .github/workflows/deploy.yml
name: deploy to deta space

on: 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    name: deploy to deta space
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: lizheming/deta-action@master
      with:
        access_token: "sS1EQxP2mzKysxc3mhxBdEHcyWEhzDR4"
        id: "h2582250"
        version: "1.0.0"
        notes: "Release automatically with GitHub deta action"
        listed: false
